// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuOlmTwmsLWWfrH7G9jRZ0_H_zQqqNSDE',
    appId: '1:262142953146:web:7aaa6247a5e6a4abaf6483',
    messagingSenderId: '262142953146',
    projectId: 'fluttersnake-28683',
    authDomain: 'fluttersnake-28683.firebaseapp.com',
    storageBucket: 'fluttersnake-28683.appspot.com',
    measurementId: 'G-PW8K2GYD88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZk0Vh1p_cKhALiFrh6_SKbEeOSOQtVaw',
    appId: '1:262142953146:android:9f7469d6cc6191a0af6483',
    messagingSenderId: '262142953146',
    projectId: 'fluttersnake-28683',
    storageBucket: 'fluttersnake-28683.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARPV-bvwZww1DUWMatM9EMiaBT82bZW8g',
    appId: '1:262142953146:ios:701394681372ef46af6483',
    messagingSenderId: '262142953146',
    projectId: 'fluttersnake-28683',
    storageBucket: 'fluttersnake-28683.appspot.com',
    androidClientId: '262142953146-mc8i04j9hggsahp3rg1uf5hvfli7hm82.apps.googleusercontent.com',
    iosClientId: '262142953146-j2v0puk6bk6k1p322a32e2mmtq0k0e2t.apps.googleusercontent.com',
    iosBundleId: 'com.bme.vik.flutter.hazi.fluttersnakehazi',
  );
}
